function buildCategoryItem(label, matchers = null) {
  return {
    label,
    matchers: Array.isArray(matchers) && matchers.length ? matchers : [label],
  }
}

export const stockCategoryGroups = [
  {
    title: 'Kategori Khusus: Peralatan (Alat)',
    level: 5,
    items: [buildCategoryItem('Peralatan (Alat)', ['alat'])],
  },
  {
    title: 'Kategori 1 Kata',
    level: 1,
    items: [
      buildCategoryItem('Adaptor'),
      buildCategoryItem('Alternator'),
      buildCategoryItem('Amplifier'),
      buildCategoryItem('Apollo'),
      buildCategoryItem('Backcover'),
      buildCategoryItem('Baskit'),
      buildCategoryItem('Baut'),
      buildCategoryItem('Bearing'),
      buildCategoryItem('Box'),
      buildCategoryItem('Bracket'),
      buildCategoryItem('Bubuk'),
      buildCategoryItem('Cairan'),
      buildCategoryItem('Cleaner'),
      buildCategoryItem('Coil'),
      buildCategoryItem('Comp'),
      buildCategoryItem('Cond'),
      buildCategoryItem('Copling'),
      buildCategoryItem('Corong'),
      buildCategoryItem('Custom'),
      buildCategoryItem('Dodol'),
      buildCategoryItem('Drier'),
      buildCategoryItem('Evap'),
      buildCategoryItem('Expansi'),
      buildCategoryItem('Fanshrood'),
      buildCategoryItem('Filter'),
      buildCategoryItem('Fitting'),
      buildCategoryItem('Fogging'),
      buildCategoryItem('Freon'),
      buildCategoryItem('Gasket'),
      buildCategoryItem('Gigi'),
      buildCategoryItem('Grill'),
      buildCategoryItem('Insulok'),
      buildCategoryItem('Kalender'),
      buildCategoryItem('Kancing'),
      buildCategoryItem('Karet'),
      buildCategoryItem('Kawat'),
      buildCategoryItem('Kipas'),
      buildCategoryItem('Klem'),
      buildCategoryItem('Kleman'),
      buildCategoryItem('Klep'),
      buildCategoryItem('Knop'),
      buildCategoryItem('Kunci'),
      buildCategoryItem('Laher'),
      buildCategoryItem('Laktun'),
      buildCategoryItem('Lem'),
      buildCategoryItem('Liquid'),
      buildCategoryItem('Lover'),
      buildCategoryItem('Manifold'),
      buildCategoryItem('Mc'),
      buildCategoryItem('Mesin'),
      buildCategoryItem('Meteran'),
      buildCategoryItem('Muffler / Mufler', ['muffler', 'mufler']),
      buildCategoryItem('Nepel'),
      buildCategoryItem('Nut'),
      buildCategoryItem('Oli'),
      buildCategoryItem('Oriface'),
      buildCategoryItem('Packing'),
      buildCategoryItem('Pentil'),
      buildCategoryItem('Pipa'),
      buildCategoryItem('Pisau'),
      buildCategoryItem('Plakban'),
      buildCategoryItem('Plat'),
      buildCategoryItem('Potensio'),
      buildCategoryItem('Power'),
      buildCategoryItem('Pully'),
      buildCategoryItem('Raber'),
      buildCategoryItem('Rangka'),
      buildCategoryItem('Relay'),
      buildCategoryItem('Resistor'),
      buildCategoryItem('Rotor'),
      buildCategoryItem('Rumah'),
      buildCategoryItem('Seal'),
      buildCategoryItem('Sekring'),
      buildCategoryItem('Selang'),
      buildCategoryItem('Selenoid'),
      buildCategoryItem('Servo'),
      buildCategoryItem('Shock'),
      buildCategoryItem('Snapring'),
      buildCategoryItem('Socket'),
      buildCategoryItem('Spicer'),
      buildCategoryItem('Spull'),
      buildCategoryItem('Stelan'),
      buildCategoryItem('Switch'),
      buildCategoryItem('Swivel'),
      buildCategoryItem('Thermister'),
      buildCategoryItem('Thermometer'),
      buildCategoryItem('Thermostat'),
      buildCategoryItem('Tombol'),
      buildCategoryItem('Tracker / Tracket / Trak / Traker', ['tracker', 'tracket', 'trak', 'traker']),
      buildCategoryItem('Tutup'),
      buildCategoryItem('Unit'),
      buildCategoryItem('Utilux'),
      buildCategoryItem('Vacum'),
      buildCategoryItem('Valve'),
    ],
  },
  {
    title: 'Kategori 2 Kata',
    level: 2,
    items: [
      buildCategoryItem('Air cleaner'),
      buildCategoryItem('Center piece'),
      buildCategoryItem('Coling unit'),
      buildCategoryItem('Control valve'),
      buildCategoryItem('Double blower'),
      buildCategoryItem('Extra fan'),
      buildCategoryItem('Filter cond'),
      buildCategoryItem('Filter udara'),
      buildCategoryItem('Head cylinder'),
      buildCategoryItem('Hose clamp'),
      buildCategoryItem('Idle pully'),
      buildCategoryItem('Idle up'),
      buildCategoryItem('Kabel ties'),
      buildCategoryItem('Kipas blower'),
      buildCategoryItem('Kipas bus'),
      buildCategoryItem('Kipas fan'),
      buildCategoryItem('Kipas radiator'),
      buildCategoryItem('Mesin pres / press', ['mesin pres', 'mesin press']),
      buildCategoryItem('Mesin receclyng / recycling', ['mesin receclyng', 'mesin recycling']),
      buildCategoryItem('Motor blower'),
      buildCategoryItem('Motor fan'),
      buildCategoryItem('Motor rad'),
      buildCategoryItem('Name plat'),
      buildCategoryItem('Nepel comp'),
      buildCategoryItem('Nepel double'),
      buildCategoryItem('Nepel freon'),
      buildCategoryItem('Nepel las'),
      buildCategoryItem('Nepel pentil'),
      buildCategoryItem('Nepel seal'),
      buildCategoryItem('Nepel switch'),
      buildCategoryItem('Nepel t'),
      buildCategoryItem('Nepel tancap'),
      buildCategoryItem('Pressure switch'),
      buildCategoryItem('Seal gelang'),
      buildCategoryItem('Seal kotak'),
      buildCategoryItem('Seal oring'),
      buildCategoryItem('Seal selang'),
      buildCategoryItem('Seal service'),
      buildCategoryItem('Seal spin'),
      buildCategoryItem('Seal valve'),
      buildCategoryItem('Sekring box'),
      buildCategoryItem('Service valve'),
      buildCategoryItem('Sight glass'),
      buildCategoryItem('Spull gulungan'),
      buildCategoryItem('Stelan bracket'),
      buildCategoryItem('Stelan ip'),
      buildCategoryItem('Switch control'),
      buildCategoryItem('Switch drier'),
      buildCategoryItem('Switch geser'),
      buildCategoryItem('Switch temp'),
      buildCategoryItem('T air'),
      buildCategoryItem('T idle'),
      buildCategoryItem('Tool kit'),
      buildCategoryItem('Vacum pump'),
      buildCategoryItem('Van belt'),
      buildCategoryItem('Water pump'),
    ],
  },
  {
    title: 'Kategori 3 Kata',
    level: 3,
    items: [
      buildCategoryItem('Fitting las sambung'),
      buildCategoryItem('Kipas blower d/b'),
      buildCategoryItem('Laher head cylinder'),
      buildCategoryItem('Laher idle pully'),
      buildCategoryItem('Motor blower taiwan'),
      buildCategoryItem('Mufler nd fitting'),
      buildCategoryItem('Nepel double tancap'),
      buildCategoryItem('Seal oring set'),
      buildCategoryItem('Stelan idle pully'),
      buildCategoryItem('Tutup cover filter'),
      buildCategoryItem('Tutup pentil comp'),
      buildCategoryItem('Vacum idle up'),
    ],
  },
  {
    title: 'Kategori 4 Kata',
    level: 4,
    items: [
      buildCategoryItem('Fitting joint alm press'),
      buildCategoryItem('Manifold meteran + selang'),
      buildCategoryItem('Mesin pres selang gantung'),
      buildCategoryItem('Mesin press selang manual'),
      buildCategoryItem('Mesin press selang tangan'),
    ],
  },
]
